spring:
  datasource:
    url: jdbc:mysql://150.158.50.190:3306/i18n?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '@Zby746459'
    driver-class-name: com.mysql.jdbc.Driver



